AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AwsAccountID:
    Type: String
    Description: Your AWS Account ID

Resources:
  ConnectHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ConnectHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref DynamoDBFullAccessPolicy
  DisconnectHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DisconnectHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref DynamoDBFullAccessPolicy
  AccessApiGatewayPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: AccessApiGatewayPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: execute-api:ManageConnections
            Resource:
              - !Sub "arn:aws:execute-api:*:${AwsAccountID}:*/*/POST/@connections/*"
          - Effect: Allow
            Action: execute-api:ManageConnections
            Resource:
              - !Sub "arn:aws:execute-api:*:${AwsAccountID}:*/*/GET/@connections/*"
  DefaultHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DefaultHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref AccessApiGatewayPolicy
  SendMessageHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SendMessageHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - !Ref AccessApiGatewayPolicy
        - !Ref DynamoDBFullAccessPolicy
  SetConnectionDetailHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SetConnectionDetailHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref DynamoDBFullAccessPolicy

  DynamoDBFullAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DynamoDBFullAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetRecords
              - dynamodb:Query
              - dynamodb:ConditionCheckItem
            Resource:
              - !Sub "arn:aws:dynamodb:*:${AwsAccountID}:table/Connections"
              - !Sub "arn:aws:dynamodb:*:${AwsAccountID}:table/Messages"
  DynamoDBReadAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DynamoDBReadAccessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetRecords
              - dynamodb:Query
              - dynamodb:ConditionCheckItem
            Resource:
              - !Sub "arn:aws:dynamodb:*:${AwsAccountID}:table/Connections"
              - !Sub "arn:aws:dynamodb:*:${AwsAccountID}:table/Messages"
  MessageRetrievalHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MessageRetrievalHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref AccessApiGatewayPolicy
        - !Ref DynamoDBReadAccessPolicy
  TranslationHandlerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TranslationHandlerServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/TranslateReadOnly
        - !Ref AccessApiGatewayPolicy
